name = "DiffFusion"
uuid = "be7e520c-a8fa-4f26-8f65-6d6d1049182e"
authors = ["Sebastian Schlenkrich <sebastian.schlenkrich@frame-consult.de> and contributors"]
version = "0.0.1"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
